# Generated by Django 4.2.3 on 2024-01-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinate_systems', '0002_alter_coordinates_x_coo_alter_coordinates_y_coo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D48_file', models.FileField(upload_to='uploads/')),
                ('D96_file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
