# Generated by Django 4.2.3 on 2024-03-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinate_systems', '0003_yourmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
